# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rahul Thapa
title: MSc Data Science Student | Data Analyst | ML Enthusiast
email: rahulmangar96@gmail.com
website: https://rahultahpa33.github.io/datasciencportfolio/

# Dark Mode
darkmode: false

# Social links
github_username: rahulthapa33
linkedin_username: rahul-t-09208714a

# Additional icon links
additional_links:
- title: Resume (PDF)
  icon: fas fa-file-pdf
  url: https://your-resume-link.com  # Replace with actual file or Google Drive link

# About Section
about_profile_image: images/profile.jpg
about_content: |
  I am a postgraduate Data Science student at Leeds Beckett University with a strong foundation in Python, SQL, and machine learning. Previously worked as a Full Stack Developer with experience in SaaS applications, database systems, and data-driven web apps. I'm passionate about applying data science to solve real-world problems in analytics and automation.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: NY Airport ETL Data Pipeline
        link: https://github.com/rahulmangar96/ny-airport-etl
        additional_links:
          - title: View on GitHub
            icon: fab fa-github
            url: https://github.com/rahulmangar96/ny-airport-etl
        quote: >
          ETL pipeline to process and analyze NYC airport complaints and flight data.
        description: |
          Designed relational schemas, built SQL-based pipelines, and developed dashboards in Oracle APEX to track complaint trends and performance indicators.

      - layout: top-middle
        title: Vehicle Rental Management System
        link: https://github.com/rahulmangar96/vehicle-rental-apex
        additional_links:
          - title: View on GitHub
            icon: fab fa-github
            url: https://github.com/rahulmangar96/vehicle-rental-apex
        quote: >
          End-to-end database application for a rental car system using Oracle APEX.
        description: |
          Implemented master-detail forms, automated triggers, and reporting dashboards with integrated PL/SQL logic.

      - layout: top-middle
        title: Chrome Extension for Safe Browsing
        link: https://github.com/rahulmangar96/chrome-safe-browsing
        additional_links:
          - title: View on GitHub
            icon: fab fa-github
            url: https://github.com/rahulmangar96/chrome-safe-browsing
        quote: >
          Browser extension that classifies malicious sites using ML.
        description: |
          Developed using JavaScript and a backend classification model. Helps users stay safe online through real-time monitoring and dynamic website scoring.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Asti Infotech
        sub_title: Full Stack Developer
        caption: Jun 2022 – Jul 2024
        quote: >
          Delivered scalable SaaS solutions and optimized data systems for enterprise clients.
        description: |
          - Developed RESTful APIs, dashboards, and back-end logic for dynamic reporting.  
          - Wrote complex SQL queries and integrated analytics features into production systems.  
          - Contributed to cross-functional team success by aligning development with data goals.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Leeds Beckett University
        caption: Sep 2024 – Present
        sub_title: MSc Data Science
        description: |
          Relevant Modules:  
          - Database Systems  
          - Intelligent Systems and Machine Learning  
          - Data Warehouse Models and Approaches  
          - Data Analytics and Visualization  
          Tools: Python, SQL, Tableau, Spark, Power BI

      - layout: left
        title: Veltech Institute of Science & Technology
        caption: Jun 2017 – May 2021
        sub_title: BSc Computer Science

  - title: Additional Information
    layout: text
    content: |
      - Currently on a Student Visa; eligible for the UK Graduate Route post-study work visa.  
      - Open to employers offering visa sponsorship for long-term roles.  
      - Strong communication and problem-solving skills.  
      - Actively seeking data science internships or graduate roles starting 2025.

# Footer
footer_show_references: true
